all:
  children:
    ios:
      hosts: 
        SWEx-dc1-core1: 
        SWEx-dc1-core2: 
        SWEx-dc2-core1: 
        SWEx-dc2-core2: 
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_ssh_pass: '{{password}}'
        ansible_user: '{{username}}'
  vars:
    ansible_python_interpreter: /usr/bin/python3
